[package]
name = "MinnowSnap"
version = "0.1.0"
edition = "2024"
authors = ["Lortuante"]

[workspace]
members = ["build-tools"]

[dependencies]
mimalloc = "0.1"
cxx = "1.0.192"
cxx-qt = "0.8"
cxx-qt-lib = { version = "0.8", features = ["qt_full"] }
image = { version = "0.25", default-features = false, features = ["rayon", "png", "jpeg"] }
xcap = { version = "0.8", features = ["image"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.11"
arboard = "3.6"
dirs = "6.0"
oxipng = { version = "10.0", default-features = false, features = ["parallel", "zopfli", "filetime"] }
global-hotkey = { version = "0.7", features = ["tracing"] }
single-instance = "0.3"
config = { version = "0.15", default-features = false, features = ["async", "toml"] }
toml = "0.9"
directories = "6.0"
auto-launch = "0.5"
font-kit = "0.14"
notify-rust = "4"
rodio = "0.21.1"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-app-kit = { version = "0.3", features = ["NSApplication"] }

[build-dependencies]
cxx-qt-build = { version = "0.8", features = ["link_qt_object_files"] }
cc = "1"
build-tools = { path = "build-tools" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[package.metadata.bundle]
identifier = "com.lortunate.minnowsnap"
icon = ["assets_icons/icon.icns", "assets_icons/icon.ico"]
osx_info_plist_exts = ["resources/Info.plist.extra"]
