[package]
name = "build-tools"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
image = { workspace = true, features = ["default"] }
walkdir = { workspace = true }
quick-xml = { workspace = true }
ico = { workspace = true }
winres = { workspace = true }
